language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

sudo: required

android:
  components:
    - build-tools-23.0.0

before_script: chmod +x gradlew 

script: ./gradlew

notifications:
  email: false
