language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

sudo: required

android:
  components:
    - platform-tool
    - tool
    - android-23
    - build-tools-23
    - extra-android-m2repository
    - extra-google-m2repository

before_script: chmod +x gradlew 

script: ./gradlew

notifications:
  email: false
