language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.0.0

before_script:

script: ./gradlew

notifications:
  email: true

before_install:
  - pip install codecov
after_success:
  - codecov